name: fzregex
description: "Validating: Phone, Name, PostalCode, Email, URL, Currency, IP Address, Date, Time, HTMLTags, Password (Strong), Password (Medium), Credit Card.\n for Dart/Flutter Developers."
version: 1.0.0
homepage: https://github.com/FrazileDevelopers/FzRegex

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # assets:
  #   - images/

  # fonts:
  #   - family: Google
  #     fonts:
  #       - asset: fonts/google-Regular.ttf
  #       - asset: fonts/google-Italic.ttf
  #         style: italic
